### ISSUE TITLE
how to freely copy/move file between PiRATE and Ubutu?

### ISSUE THREAD

**Issue by wangj2009** [JBerthelier/PiRATE#14]
Dear Jeremy,
     Could you tell me how to freely copy/move files between PiRATE and Ubutu?
     I use ubuntu 18.04. I shared a Desktop/VM-shared-folder between VM and ubuntu.
     Thank you very much,
wj

**Comment by JBerthelier** [comment]
Hi wj,
You can realise this task through various ways, for exemple you can transfer:

with a usb key
with ftp
with internet (cloud)
Once your data is on the virtual machine you can copy-past in to the directory
"administrator@pba.fr" in order to transfert into Galaxy (see manual).

I hope this will help you,

Best regards,

Jérémy
