### ISSUE TITLE
FASTQ to FASTA error

### ISSUE THREAD

**Issue by pwkooij** [JBerthelier/PiRATE#27]
When trying to transform my FASTQ to FASTA I get the following error:

fastq_to_fasta: Invalid quality score value (char '#' ord 35 quality value -29) on line 4 gzip: stdout: Broken pipe

**Comment by JBerthelier** [comment]
Dear pwooij, 

Thank you for using PiRATE-Galaxy, 

I think your data migh have a problems, because this tool works well for me and others. 
By the way, I didn't build the  fastq_to_fasta tool, it is part of the tool shed of Galaxy.

If you want to change your fastq to fasta with an other way, 
please check on google to find linux commands, there is a high number of topics about it.

Example:
for example: https://www.biostars.org/p/85929/

Best, 

Jeremy

**Comment by pwkooij** [comment]
After following the prep instructions in the tutorial, and changing the format from fastqillumina to fastqsanger it was fixed
