### ISSUE TITLE
Error with Helsearch

### ISSUE THREAD

**Issue by JBerthelier** [JBerthelier/PiRATE#3]
A PiRATE user reported this error with Helsearch:

Fatal error: Exit code 1 () [formatdb] WARNING: Cannot add sequence number 1 (lcl|1_./working/GCCCTGA_CA_TCAGGGC_156) because it has zero-length. [formatdb] FATAL ERROR: Fatal error when adding sequence to BLAST database. rm: impossible de supprimer «./working/GCCCGC_AAGA_GCGGGC_2/GCCCGC_AAGA_GCGGGC_2.nhr»: Aucun fichier ou dossier de ce type rm: impossible de supprimer «./working/GCCCGC_AAGA_GCGGGC_2/GCCCGC_AAGA_GCGGGC_2.nsq»: Aucun fichier ou dossier de ce type [formatdb] ERROR: ./working/TCCAAT_AAT_ATTGGA_2/TCCAAT_AAT_ATTGGA_2.nhrOutput Blast-def-line-set.E.<title> Invalid value(s) [9] in VisibleString [genome_P#2379729#2379929 ...] [formatdb] ERROR: ./working/TCCAAT_AAT_ATTGGA_2/TCCAAT_AAT_ATTGGA_2.nhrOutput Blast-def-line-set.E.<title> Invalid value(s) [9] in VisibleString [genome_P#28421039#28421239 ...] cp: impossible d'évaluer «/home/jeremy/Pipeline/helsearch1.0/helitron_contain/helitron.fa»: Aucun fichier ou dossier de ce type

To fix this error, the input sequences must have a width of 60 pb with per lines. 

Best,

**Comment by anandksrao** [comment]
[InputFile_Details_Attributes.txt](https://github.com/JBerthelier/PiRATE/files/3640382/InputFile_Details_Attributes.txt)
[TAIR10_Arabidopsithaliana_Chr1_PiRaTE_HelSearchFAIL_LTRHarvestPASS.txt](https://github.com/JBerthelier/PiRATE/files/3640383/TAIR10_Arabidopsithaliana_Chr1_PiRaTE_HelSearchFAIL_LTRHarvestPASS.txt)
![Screen Shot 2019-09-22 at 8 55 54 PM](https://user-images.githubusercontent.com/11311424/65397821-24d57780-dd81-11e9-97ab-9526625ba2ba.png)

- I tried just running HelSearch with input test fasta file = Chr1 of TIR10 release of a plant species - Arabidopsis thaliana. 
- I used fold -w 60 to insure the input file has line width = 60.
- However, **HelSearch returned error** from within your PiRaTE Galaxy VM.

Some more details below:

**Outcomes**: 

- I tried running helsearch, but it failed. 
- To make sure the input file is OK, I tried it with LTRHarvest, the results were generated successfully. This means input file is OK ?!
- But, same input with MGEScan-nonLTR failed....

See error logs and other details in attached text file: 
Filename = TAIR10_Arabidopsithaliana_Chr1_PiRaTE_HelSearchFAIL_LTRHarvestPASS.txt

**Request 1** - Could you please advise on how to proceed so that I can successfully run HelSearch and generate complete results?

Please see 2nd text file attached for Chr1 input file's details & attributes. 
Filename = InputFile_Details_Attributes.txt
**Request 2** - Could you please tell me if there are there any input file attributes that are incompatible with helsearch?  Do I need to change anything about this input file?

Thanks, in advance, for your prompt responses to my questions and requests above.

**Comment by pwkooij** [comment]
I have changed the input file with 60bp per line, but I still get an error for Helsearch

`atal error: Exit code 1 () [formatdb] ERROR: ./working/GCAGGT_CGA_ACCTGC_5/GCAGGT_CGA_ACCTGC_5.nhrOutput Blast-def-line-set.E.<title> Invalid value(s) [9] in VisibleString [genome_P#12826044#12826244 ...] [formatdb] ERROR: ./working/GCAGGT_CGA_ACCTGC_5/`
