### ISSUE TITLE
Error with Helsearch

### ISSUE THREAD

**Issue by pwkooij** [JBerthelier/PiRATE#31]
I have changed the input file with 60bp per line, but I still get an error for Helsearch

```
Fatal error: Exit code 1 () 

[formatdb] ERROR: ./working/GCAGGT_CGA_ACCTGC_5/GCAGGT_CGA_ACCTGC_5.nhrOutput Blast-def-line-set.E.<title> 

Invalid value(s) [9] in VisibleString [genome_P#12826044#12826244 ...] 

[formatdb] ERROR: ./working/GCAGGT_CGA_ACCTGC_5/
```

**Comment by JBerthelier** [comment]
Dear pwkooij, 

Sevreral users reported me errors with helsearch.

Because this tool seems to be very capricious and generate numerous false positifs, 
it will be removed in the new Pirate version.

I advise you to not use it in your analyses. 

If there is Helitron in the genome you are studying, they should be found by repeatitiveness-based approach tools such as TEdenovo or Repeatscout.

 Best

Jeremy

**Comment by pwkooij** [comment]
Hi Jeremy

Thanks for your response! I will skip the analysis.

Cheers
Pepijn
