### ISSUE TITLE
How to upload huge data on the virtual computer to galaxy via FTP?

### ISSUE THREAD

**Issue by liulu0827** [JBerthelier/PiRATE#34]
Hi,
I have problems with uploading data. My Illumina data is ~70G, it's over 1G, so I tried to use ftp to upload my data. My data files have already in my virtual computer. Here are two methods I tried:

1)  copy-past my files in the directory “administrator@pba.fr” of the PiRATE-VM /home/Jeremy/Documents/administrator@pba.fr.
It dosen't work. I saw the files in the administrator@pba.fr, but I saw nothing when I selected "Choose FTP files" to upload data in the galaxy web.

2) I used FileZilla to transfer files. Host:134.246.55.42    usrname: my_email    password:****.
It dosen't work. FileZilla told me "Couldn't connect to server".
But when used the HOST: usegalaxy.org, I succeeded to connect to server and upload files.

Is there anything wrong with my operation? And how can I solve this problem----upload data via FTP?

Thank you for your attention and hope for your solution.

**Comment by JBerthelier** [comment]
Dear liulu0827, 

Thank you for your message, 

At know I do not know why your file doesn't appear when you "chose FTP files".

However, I would not recommend to use PiRATE with a huge data file of 70Gb.
It is too much for this Virtual-machine version of PiRATE.

Moreover, you want probably use RepeatExplorer and dnaPipeTEs with your illumina data, 
but those tools do not requiere a huge Illumina reads data file. Because they first do a random sampling of reads. Thus, a few amount of of your 70Gb reads will be in fact used. 
You should decrease the amount of reads. Two Illumina paired file of 5-10Gb each should be fine. 
Please check the dnaPipeTEs and RepeatExplorer papers to be aware about that point.

2.about the Fizella transfert please check this issue
https://github.com/JBerthelier/PiRATE/issues/28

Best regards

Jeremy
