### ISSUE TITLE
Does it necessary to have an assembled genome to run PiRATE pipeline

### ISSUE THREAD

**Issue by majie5976** [JBerthelier/PiRATE#37]
Hi @JBerthelier , 
Hope all is fine with you. Before running PiRATE pipeline I just want to confirm that, Does it necessary to have an assembled genome to run PiRATE pipeline. Because species I'm working on not possible to have an assembled genome due to large genome size. Can I use approach 4 (build repeated elements) in step one, then proceed the following steps as it is. The questions why I'm asking because I checked the final step TEannot there is two input requirements 
1. genomic Sequences (Enter the genome assembly) 
2. TE Library (the manually constructed TE Libraries) If I'm not worng. 
Your suggestions would be appreciated !
Sorry due to Server link down problem this issue gets duplicated, allow me to delete one of them.
Thanks
Regards,
Majie

**Comment by JBerthelier** [comment]
Dear Majie, 

Thanks for your message and interest about PiRATE.

PiRATE is very flexible, you can only use only the tools that are interesting for your study. It a kind of platform of lot of tools to achieve what you want.

Thus, you don't need to have a genome assembly to use some tools.

For exemple if you want to know what kind a TEs are in the genome of the species you are studying, you can for sure, only used the tools of the approches 4 and then use PASTEC (classification step).
You will got a library of TEs that are in the genome. 

But, because you do not have a genome assembly you will not use the next tools for the TE genome annotation (TEannot).

Hope this will help you, 

Best regards, 

Jeremy

**Comment by majie5976** [comment]
Hi @JBerthelier ,
Got it, Many Thanks.
