### ISSUE TITLE
PiRATE pipeline.

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#38]
Hello, can we use PiRATE for retrieval and annotation of transposable elements in fungal genomes, specifically Basidiomycota?

**Comment by JBerthelier** [comment]
Dear Lukanyo, 

Yes, PiRATE can be use for all organisms!
It will only be limited by your computational force, because at now it only work on a local computer.
If your organisms has a relative small genome (less than 500 Mb) it should be fine with a good computer. 
How long is the genome assembly? What is your computational configuration?

As example: I am using 10 cores and 28 Mb of memory for the Virtual Machine of PiRATE installed on my local computer.  

Best 

Jeremy

**Comment by Lukanyo12** [comment]
Thank you for your reply! I was worried. My genome assemblies ranges from
60 to 90 Mb.Well my CPU has 2 cores on window 10.

**Comment by JBerthelier** [comment]
Dear Lukanyo, 

No problem! According that your are going to analyse a relative small genome size, the PiraTE should be able to run on your local computer. But for sure it gonna take a time for the tool to finish. The big one tools (TEdenovo, PASTEC and TEannot) will probably take longer time than other tools to finish.

Best regards, 

Jeremy

**Comment by Lukanyo12** [comment]
Any idea of how can I overcome that and make  it fast maybe?
