### ISSUE TITLE
Single Transposable elements library

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#42]
Hello Berthelier
Forgive me for dozens of questions, It's just that I want to make use of this tool as much as I can. 
Since you were interested in potentially autonomous TEs  in your study, and you focused on them mostly.  What if for example in my case, my goal is to identify, classify and annotated TEs in genomes of interest. After classification, I want to group my elements as "class I retrotransposons" "class II DNA transposons" and "un-categorized elements" . Following classification, I wish to cluster  the TE consensus sequences into families using MCL. Then, create a TE library for respective organism and perform a genome-wide annotation using TEannot pipeline.

**Comment by JBerthelier** [comment]
Dear Lukanyo12,

Yes this is good, you can build a single TE library for each respective organisms, 
but I would advise you to only use the classified Class I and Class II in your libraries. 
I would not use the unclassified, because it could be composed by several false positives.

Best regards,

Jeremy

**Comment by Lukanyo12** [comment]
Thank you! Just a follow up question. how can I determine then the content of for example Class I TEs, Classs II TEs, unknown elements and Total TEs content?
